# http://travis-encrypt.github.io/
# http://lint.travis-ci.org/
language: groovy
install: gradle check
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
env:
   global:
   - secure: fSUu6LU/2tEkW9G4jftJMILzQv7rg1Kp0O0XPqeCFO3EtDNEJU2OvHRlt3Hs6sa9gLqACdt3zlkfsg9p44viNYtR93rcLMabXaF5mR0EO/NaLpKoa+830rleJl0IKX2OTqL4CY8W7uMLKd07Uwpv3y1rz16dnQsltuRYGaIAjG6/XS20bwCUXa1jEGpgmV1FeIEgR55UerchXeVBhajxluVuyhzJjReC5vR9tutlcMhz9IuUgWE3ktZyHUIs0pi45qjOmMeDf48zGv2GT/Dyxqc8O9JnjHM3vciYcbe5vVKHlmUC47xSpBRhqW5oUoiNYwfSsuprQO0+QXFkUsKQJabdO+6RziR46NaUDW2FLkJXgSDs3xyhFZ27xbjIim1nEOQEIRKVZPNkUiiWsP2r8fMqyBKnEbpFgnINJa+RTjsXEqTZ5uMVIo8rWOAumssvbx8iiot0i5GosdZr3NidzOsk68eoW5QWXzprliKAJdIE8xF8XU5h1k1sgPV3CC+smZxtzcp77FWzmD8DPW63IpyX+r3YE5QH+kfoEhYZhPRxR/nqE5Jcru1zGR9e2+2ukCZK9aldMI14oHuOgvdnBmmYEOsUfFG1G2u78sjZ/b+2k66eQaij8LWWLD0gkIr3mrFVLVbXdjieFYQNUgQsk2hJ6djb5iuNhSIJHIaQdOo=
